apiVersion: v1
kind: Service
metadata:
  name: moscow-time-service
spec:
  selector:
    app: moscow-time
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort
