apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moscow-time-go-ingress
  annotations:
    # Use nginx as ingress controller
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: moscow-time-go.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moscow-time-go-service
                port:
                  number: 8080
