apiVersion: v1
kind: Service
metadata:
  name: moscow-time-go-service
spec:
  selector:
    app: moscow-time-go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
